### Get all alerts
GET http://localhost:5238/alerts

### Post a new alert
POST http://localhost:5238/alert
Content-Type: application/json

{
  "message": "TEST111","soundValue": 500
}

### Filter today's alerts
GET http://localhost:5238/AlertLog?Filter=today

### Filter Last 24
GET http://localhost:5238/AlertLog?Filter=last24h

### Filter weeks alert
GET http://localhost:5238/AlertLog?Filter=week

### Filter all door alerts
GET http://localhost:5238/AlertLog?Filter=door

### Filter all loud alerts
GET http://localhost:5238/AlertLog?Filter=loud

### update live status
POST http://localhost:5238/update-live-status
Content-Type: application/json

{
  "doorOpen": true,
  "soundValue": 45
}

### Get live status
GET http://localhost:5238/live-status